vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xilinx_vip
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/axi_infrastructure_v1_1_0
vlib modelsim_lib/msim/smartconnect_v1_0
vlib modelsim_lib/msim/axi_protocol_checker_v2_0_2
vlib modelsim_lib/msim/axi_vip_v1_1_2
vlib modelsim_lib/msim/processing_system7_vip_v1_0_4
vlib modelsim_lib/msim/lib_cdc_v1_0_2
vlib modelsim_lib/msim/proc_sys_reset_v5_0_12
vlib modelsim_lib/msim/gigantic_mux
vlib modelsim_lib/msim/xlconcat_v2_1_1
vlib modelsim_lib/msim/blk_mem_gen_v8_3_6
vlib modelsim_lib/msim/axi_bram_ctrl_v4_0_14
vlib modelsim_lib/msim/blk_mem_gen_v8_4_1
vlib modelsim_lib/msim/generic_baseblocks_v2_1_0
vlib modelsim_lib/msim/axi_register_slice_v2_1_16
vlib modelsim_lib/msim/fifo_generator_v13_2_2
vlib modelsim_lib/msim/axi_data_fifo_v2_1_15
vlib modelsim_lib/msim/axi_crossbar_v2_1_17
vlib modelsim_lib/msim/lib_pkg_v1_0_2
vlib modelsim_lib/msim/lib_srl_fifo_v1_0_2
vlib modelsim_lib/msim/lib_fifo_v1_0_11
vlib modelsim_lib/msim/axi_datamover_v5_1_18
vlib modelsim_lib/msim/axi_sg_v4_1_9
vlib modelsim_lib/msim/axi_cdma_v4_1_16
vlib modelsim_lib/msim/axi_protocol_converter_v2_1_16
vlib modelsim_lib/msim/axi_clock_converter_v2_1_15
vlib modelsim_lib/msim/axi_dwidth_converter_v2_1_16

vmap xilinx_vip modelsim_lib/msim/xilinx_vip
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap axi_infrastructure_v1_1_0 modelsim_lib/msim/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 modelsim_lib/msim/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_2 modelsim_lib/msim/axi_protocol_checker_v2_0_2
vmap axi_vip_v1_1_2 modelsim_lib/msim/axi_vip_v1_1_2
vmap processing_system7_vip_v1_0_4 modelsim_lib/msim/processing_system7_vip_v1_0_4
vmap lib_cdc_v1_0_2 modelsim_lib/msim/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_12 modelsim_lib/msim/proc_sys_reset_v5_0_12
vmap gigantic_mux modelsim_lib/msim/gigantic_mux
vmap xlconcat_v2_1_1 modelsim_lib/msim/xlconcat_v2_1_1
vmap blk_mem_gen_v8_3_6 modelsim_lib/msim/blk_mem_gen_v8_3_6
vmap axi_bram_ctrl_v4_0_14 modelsim_lib/msim/axi_bram_ctrl_v4_0_14
vmap blk_mem_gen_v8_4_1 modelsim_lib/msim/blk_mem_gen_v8_4_1
vmap generic_baseblocks_v2_1_0 modelsim_lib/msim/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_16 modelsim_lib/msim/axi_register_slice_v2_1_16
vmap fifo_generator_v13_2_2 modelsim_lib/msim/fifo_generator_v13_2_2
vmap axi_data_fifo_v2_1_15 modelsim_lib/msim/axi_data_fifo_v2_1_15
vmap axi_crossbar_v2_1_17 modelsim_lib/msim/axi_crossbar_v2_1_17
vmap lib_pkg_v1_0_2 modelsim_lib/msim/lib_pkg_v1_0_2
vmap lib_srl_fifo_v1_0_2 modelsim_lib/msim/lib_srl_fifo_v1_0_2
vmap lib_fifo_v1_0_11 modelsim_lib/msim/lib_fifo_v1_0_11
vmap axi_datamover_v5_1_18 modelsim_lib/msim/axi_datamover_v5_1_18
vmap axi_sg_v4_1_9 modelsim_lib/msim/axi_sg_v4_1_9
vmap axi_cdma_v4_1_16 modelsim_lib/msim/axi_cdma_v4_1_16
vmap axi_protocol_converter_v2_1_16 modelsim_lib/msim/axi_protocol_converter_v2_1_16
vmap axi_clock_converter_v2_1_15 modelsim_lib/msim/axi_clock_converter_v2_1_15
vmap axi_dwidth_converter_v2_1_16 modelsim_lib/msim/axi_dwidth_converter_v2_1_16

vlog -work xilinx_vip -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xilinx_vip "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xilinx_vip "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93 \
"C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xilinx_vip "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_2 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xilinx_vip "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/3755/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_2 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xilinx_vip "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/725c/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_4 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xilinx_vip "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \

vcom -work lib_cdc_v1_0_2 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_12 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
"../../../bd/design_1/ip/design_1_util_ds_buf_1_0/util_ds_buf.vhd" \
"../../../bd/design_1/ip/design_1_util_ds_buf_1_0/sim/design_1_util_ds_buf_1_0.vhd" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ipshared/7016/sources_1/new/housekeeping.v" \
"../../../bd/design_1/ipshared/7016/sources_1/new/main.v" \
"../../../bd/design_1/ip/design_1_main_0_0/sim/design_1_main_0_0.v" \
"../../../bd/design_1/ipshared/8a7c/hdl/cccd_v1_0_S00_AXI.v" \
"../../../bd/design_1/ipshared/8a7c/hdl/cccd_v1_0.v" \
"../../../bd/design_1/ip/design_1_cccd_0_0/sim/design_1_cccd_0_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.v" \

vlog -work gigantic_mux -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0_gigantic_mux.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/sim/bd_f60c_g_inst_0.v" \

vlog -work xlconcat_v2_1_1 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/sim/bd_f60c_slot_0_aw_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/sim/bd_f60c_slot_0_w_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/sim/bd_f60c_slot_0_b_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/sim/bd_f60c_slot_0_ar_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/sim/bd_f60c_slot_0_r_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.v" \

vlog -work blk_mem_gen_v8_3_6 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \

vcom -work axi_bram_ctrl_v4_0_14 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \

vlog -work blk_mem_gen_v8_4_1 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v" \
"../../../bd/design_1/ip/design_1_bramtest_v1_0_0_0/sim/design_1_bramtest_v1_0_0_0.v" \

vlog -work generic_baseblocks_v2_1_0 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_16 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/0cde/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_2 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_2 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_2 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_15 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/d114/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_17 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/d293/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \

vcom -work lib_pkg_v1_0_2 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_fifo_v1_0_11 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_18 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/1150/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_9 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/16f3/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_cdma_v4_1_16 -64 -93 \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/7359/hdl/axi_cdma_v4_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/design_1/ip/design_1_axi_cdma_0_0/sim/design_1_axi_cdma_0_0.vhd" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \

vlog -work axi_protocol_converter_v2_1_16 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/1229/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \

vlog -work axi_clock_converter_v2_1_15 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/d371/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work axi_dwidth_converter_v2_1_16 -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../project.srcs/sources_1/bd/design_1/ipshared/2c2b/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/b193/hdl" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2875/hdl/verilog" "+incdir+../../../../project.srcs/sources_1/bd/design_1/ipshared/2c14/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
"../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
"../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

