webtalk_init -webtalk_dir C:/Users/HEP/Documents/universefactory/ip_repo/edit_tdc_v1_0.sim/sim_1/behav/xsim/xsim.dir/data_trig_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul 18 17:21:01 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "023c1f12eb995ee68ce52923717e6493" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cf3676335e77443ebc920e9ac15b0ac5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "51" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2500 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "501 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14756_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3698397367 -regid "" -xml C:/Users/HEP/Documents/universefactory/ip_repo/edit_tdc_v1_0.sim/sim_1/behav/xsim/xsim.dir/data_trig_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/HEP/Documents/universefactory/ip_repo/edit_tdc_v1_0.sim/sim_1/behav/xsim/xsim.dir/data_trig_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/HEP/Documents/universefactory/ip_repo/edit_tdc_v1_0.sim/sim_1/behav/xsim/xsim.dir/data_trig_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
