# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param synth.incrementalSynthesisCache C:/Users/HEP/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-6252-HEP-PC/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/HEP/Documents/universefactory/ip_repo/edit_tdc_v1_0.cache/wt [current_project]
set_property parent.project_path C:/Users/HEP/Documents/universefactory/ip_repo/edit_tdc_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:microzed_7010:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/HEP/Documents/universefactory/ip_repo/tdc_1.0
  c:/Users/HEP/AppData/Roaming/Xilinx/ip_repo
  c:/Users/HEP/Documents/universefactory/ip_repo/dcd_1.0
  c:/Users/HEP/Documents/universefactory/cccd_1.0
  c:/Users/HEP/Documents/universefactory/main/main.srcs
} [current_project]
set_property ip_output_repo c:/Users/HEP/Documents/universefactory/ip_repo/edit_tdc_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/HEP/Documents/universefactory/ip_repo/tdc_1.0/src/dac_controller.v
  C:/Users/HEP/Documents/universefactory/ip_repo/tdc_1.0/src/data_recorder.v
  C:/Users/HEP/Documents/universefactory/ip_repo/tdc_1.0/hdl/tdc_v1_0_S00_AXI.v
  C:/Users/HEP/Documents/universefactory/ip_repo/tdc_1.0/src/trig_arbiter.v
  C:/Users/HEP/Documents/universefactory/ip_repo/tdc_1.0/hdl/tdc_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top tdc_v1_0 -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tdc_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tdc_v1_0_utilization_synth.rpt -pb tdc_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
