# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_trig_arbiter_0_0/design_1_trig_arbiter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_trig_arbiter_0_0 || ORIG_REF_NAME==design_1_trig_arbiter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tdc_v1_0_S00_AXI_0_0/design_1_tdc_v1_0_S00_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tdc_v1_0_S00_AXI_0_0 || ORIG_REF_NAME==design_1_tdc_v1_0_S00_AXI_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_data_recorder_0_0/design_1_data_recorder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_data_recorder_0_0 || ORIG_REF_NAME==design_1_data_recorder_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dac_controller_0_0/design_1_dac_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dac_controller_0_0 || ORIG_REF_NAME==design_1_dac_controller_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
